name: Metrics

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg
          base: yes
          base_indepth: yes
          base_hireable: no
          commits_authoring: ${{ github.actor }}
          repositories: yes
          repositories_forks: no
          repositories_affiliations: owner
          commits: yes
          commits_limit: 500
          commits_load: 100
          activity: yes
          activity_limit: 10
          activity_load: 300
          activity_days: 14
          languages: yes
          languages_limit: 8
          languages_threshold: 0%
          languages_other: yes
          languages_colors: github
          languages_sections: most-used
          languages_indepth: yes
          habits: yes
          habits_limit: 10
          habits_trim: yes
          habits_sort: recent
          achievements: yes
          achievements_threshold: C
          achievements_secrets: true
          achievements_display: detailed
          notable: yes
          notable_limit: 5
          notable_types: commit
          output_action: github-actions
          config_timezone: Europe/Paris
          config_display: 700
          config_padding: 20,30
          config_output: svg
          config_twemoji: yes
